language: python

python:
  - '3.6'

install:
  - pip install -r requirements.txt



script:
  - python -m unittest discover
  - coverage erase
  - coverage run tests/test_flaskapp.py && coverage html

after_success:
  - codecov
