language: python
python:
  - '3.6'

install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover #Kijkt naar alle classes waar test in staat en runt die
  - coverage erase
  - coverage run -m pytest && coverage html
  - pylint --errors-only main.py

after_success:
  - codecov
